### ISSUE TITLE
Pick a dataset by Monday Evening (8pm PST)

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/MDS_Winery_Dashboard#1]

**Comment by nphaterp** [comment]
My preference is to use one of the 3 datasets recommended by Joel.  Of the three i am most interested in the mental health one, but am very open to the other 2 if there are strong feelings. 

Wine: https://www.kaggle.com/zynicide/wine-reviews/data
Mental Health: https://www.kaggle.com/osmi/mental-health-in-tech-survey
Crime: https://github.com/themarshallproject/city-crime

**Comment by kmoravej** [comment]
> My preference is to use one of the 3 datasets recommended by Joel. Of the three i am most interested in the mental health one, but am very open to the other 2 if there are strong feelings.
> 
> Wine: https://www.kaggle.com/zynicide/wine-reviews/data
> Mental Health: https://www.kaggle.com/osmi/mental-health-in-tech-survey
> Crime: https://github.com/themarshallproject/city-crime

The Mental Health data set looks fine.  It is clean and It does have good variables for an interactive visualization.

**Comment by jianructose** [comment]
I'll vote for wine dataset.
Pros: a large dataset of 130k rows; sufficient variables to be interactive (country, region, variety, winery)
Cons: description column can be sentiment analysis, otherwise might be word-heavy. (It actually comes to my mind it can be a word-cloud plot)
Wine: https://www.kaggle.com/zynicide/wine-reviews/data

**Comment by mgaroub** [comment]
Wine Reviews

**Comment by kmoravej** [comment]
> I'll vote for wine dataset.
> Pros: a large dataset of 130k rows; sufficient variables to be interactive (country, region, variety, winery)
> Cons: description column can be sentiment analysis, otherwise might be word-heavy. (It actually comes to my mind it can be a word-cloud plot)
> Wine: https://www.kaggle.com/zynicide/wine-reviews/data

That is a good data set. The challenge with this data set is that most of the variables are string.

**Comment by nphaterp** [comment]
It seems that we are all in agreeance, I propose that we go ahead with the wine data.

**Comment by mgaroub** [comment]
Wine Review is chosen.
