### ISSUE TITLE
Upload screenshot/screencast as gif to repo

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/MDS_Winery_Dashboard#105]
Hey @jianridine @mgaroub @nphaterp @kmoravej ! Just a heads up that if you want to change the thumbnail in the dashboard gallery I posted on slack, you can take a screencast/screen shot and save it as a gif in your repo, currently it is your sketch that is shown there. Feel free to use this one I just took and converted for you: 

![winery-dashboard](https://user-images.githubusercontent.com/4560057/107161687-3528cb00-6953-11eb-8a4d-32c3b9531971.gif)

**Comment by mgaroub** [comment]
Thanks @joelostblom. I've uploaded a new gif of our app. You may access it here as well 

![](https://media.giphy.com/media/YUCcfHOqLzdqb4DroP/giphy.gif)

**Comment by mgaroub** [comment]
Link to gif: https://media.giphy.com/media/YUCcfHOqLzdqb4DroP/giphy.gif
@joelostblom

**Comment by joelostblom** [comment]
Great thank you!
