### ISSUE TITLE
Add two graphs to the dashboard

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/MDS_Winery_Dashboard#18]

**Comment by mgaroub** [comment]
How is it going @nphaterp?

**Comment by kmoravej** [comment]
> How is it going @nphaterp?

@nphaterp sent me the plots last night. So we are good. I did slightly modify them and I created the final version of the design. It should be fine :)

**Comment by mgaroub** [comment]
Thanks @kmoravej for clarifying.
