### ISSUE TITLE
Dashboard description

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/MDS_Winery_Dashboard#19]
The description should be about 200-300 words and live in the README.md file of your GitHub.com repository. The sketch should be linked in the README.md file of your GitHub.com repository underneath the high level description so that the image shows up on GitHub.

**Comment by nphaterp** [comment]
List of things to cover:

- We will show the distribution of counts via a heat map on a map of North America
- From dropdown lists on the side we can filter for multiple Countries, varieties and states 
- From a slider we can filter for price and points
- We will have a bar chart based on the filtered selection displaying the average price for each of the displayed wine 
- We will have an interactive scatter plot based on filtered selection displaying points vs price (gives an indicator of value) 
- we will have two side boxes. One displays the wine with highest points and the other will show the wine with the highest value (based on filter)
