### ISSUE TITLE
Reflection document

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/MDS_Winery_Dashboard#39]
In this section, your group should document on what you have implemented in your dashboard so far and explain what is not yet implemented. It is important that you include what you know is not working in your dashboard, so that your TAs can distinguish between features in development and bugs.
Reflect on what you think your dashboard does well what its limitations are, and what are good future improvements and additions. This section should not be more than 500 words and the reflection-milestone2.md document should live in your GitHub.com repo in the doc folder

**Comment by mgaroub** [comment]
Challenges to add:

- Issue with selecting multiple states
- Issue selecting multiple varieties when trying to update summary cards

**Comment by nphaterp** [comment]
- issue selecting multiple varieties to update summary cards

**Comment by mgaroub** [comment]
- Assumption: blank data in the dataset means the wine is sold out.
