### ISSUE TITLE
 Improve the README

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/MDS_Winery_Dashboard#42]
Expand on the README file to be a welcoming place for anyone coming to your project for the first time. For your project, your README should cater to at least two groups of people (on bigger projects these can be separated and put in different files):

- Those potentially interested in using your dashboard
- Those interesting in helping you develop your dashboard

Including a table of contents can be useful, **as well as a short GIF of your dashboard doing something impressive.** No matter how many nice words you put down, seeing the functionality right when they land on your GH page is very useful to evoke interest.

Example to follow: https://gitlab.com/stemcellbioengineering/context-explorer/-/blob/master/README.md

**Comment by jianructose** [comment]
done #42
