### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/MDS_Winery_Dashboard#48]
Hey Group 6,

Overall, excellent start to this project. 

Your proposal was very well written, providing a clear and reasonable outline of your intentions moving forward. I particularly enjoyed the usage scenario writeup, not only for the slight touch of humor, but also because it provided a clear explanation of how all features of the dashboard would come in handy.

With regards to the dashboard itself:
- I appreciate the clear and usable interface. The space is used well, complexity is not too high, and all interactions have a clear use case.
- General aesthetics could be improved, but as this was only a sketch, I let that slide.
- You may also have the ability to expand the map interactivity later if you have time. e.g. some additional auto-zooming, may be beneficial if you intend to split up the (physically) smaller countries into provinces/states as well. 
- You could also consider moving the selections to the map (or doubling up). There are both pros and cons to such a decision, so not necessarily a clear choice. e.g. looks nicer and allows expanded map area, but may not actually be more functional (a la many modern design "improvements")

**Comment by mgaroub** [comment]
Thank you Chris for your detailed feedback. We took your feedback into consideration and indeed it helped us to improve our dashboard. We implemented the suggested improvements and we're looking forward for your next feedback. 

Many thanks.
