### ISSUE TITLE
TODO before Next Meeting 

### ISSUE THREAD

**Issue by nphaterp** [UBC-MDS/MDS_Winery_Dashboard#5]
Next Meeting - Wednesday Jan 13th 2021

- Data will be chosen by Monday evening (8pm PST) 
- Neel, Mo & Kamal will start working on Proposal (section 1,2,3)
- We will look at other dashboards to get a better idea
- Finalize Contract (Mo) 
- Start working on contribution/license (Kamal/Mo)

Plan for Next Meeting 

- Discuss the layout for our dashboard 
- Make a plan for who is doing what with regards to what is left for the milestone

**Comment by mgaroub** [comment]
Done.
