### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by Saule-Atymtayeva** [UBC-MDS/MDS_Winery_Dashboard#61]
We are the owners of a luxury restaurant in Vancouver. In order to avoid the risks of losing time and financial resources, we are looking for a suitable option for negotiating a long-term contract for the supply of wine. The wine must be of the highest quality, as our clients have a great taste. The second criterion is distance, as we prefer a wine producer that is closer to Vancouver.
What we like about the dashboard:
-	User-friendly design.
-	The scatter chart is convenient if there is a large selection for viewing the price-rating ratio.
-	Possibility to select wine according to the criteria of a specific user.
-	Consistent theme, love the purple.
-	Easy to search for things.

What we suggest to improve:
-	It would be more convenient if the user could select a rating range and quality ratio with automatic filtering of the state list. Currently, the entire list of states drops out, including those that do not meet the criteria.
-	You can make the map clickable to visually select the required region (state). In our case, it would be easier for us to click on the map for the states located closer to Vancouver.
-	It would be better if there was a Reset button in order to reset all search criteria and start over.
- The bar chart seems a bit unnecessary given that it only shows one value.

FYI: This feedback is for your dashboard on Python (https://mds-winery-2020.herokuapp.com/). We have noticed that you have improved the R version of the dashboard, however this R version may not have been completed at the time of evaluating your dashboard.

**Comment by mgaroub** [comment]
Thank you @Saule-Atymtayeva for your feedback.
